Fix `NoMethodError` for `Pathname` fixture paths
When the `fixture_path` is defined as a `Pathname` object the
`rails_fixture_file_wrapper` fails with:

    NoMethodError:
      undefined method `strip' for #<Pathname:0x00007fab0a970e70>

This resolves the issue by ensuring the fixture path is converted into a
string prior to resolving it.